# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SacredCalendar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SacredCalendar
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SwiftKeychainWrapper'
  pod 'MaterialComponents/Buttons'
  pod 'MaterialComponents/TextFields'
  pod 'Material'

  target 'SacredCalendarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SacredCalendarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
